mysite/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

from home import views as home_views


urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    # path('__debug__/', include(debug_toolbar.urls)),
    path("ledoff/", home_views.turnLEDOff, name="turnledoff"),
    path("ledon/", home_views.turnLEDOn, name="turnledon"),
    path("ledtoggle/", home_views.toggleLED, name="toggleled"),
]


if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    # path('__debug__/', include(debug_toolbar.urls)),
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

home/models.py
from django.db import models

from wagtail.core.models import Page
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel, PageChooserPanel, MultiFieldPanel
from wagtail.images.edit_handlers import ImageChooserPanel

from django.utils.html import format_html

DONOTDISTURB = "DND"
OPEN = "OPN"
CLOSED = "CLS"

ROOM_STATE_CHOICES = [
    (DONOTDISTURB, "Bitte nicht stören!"),
    (OPEN, "Wir haben geöffnet!"),
    (CLOSED, "Wir haben geschlossen!"),
]


class HomePage(Page):
    """ Home page model. """

    max_count = 1

    template = "home/home_page.html"

    banner_title = models.CharField(
        "Nachricht des Tages",
        max_length=65,
        blank=True,
        null=False,
    )

    banner_subtitle = RichTextField(
        "Details zur Nachricht des Tages",
        features=[
            "bold",
            "italic",
            "h2",
            "h3",
            "hr",
        ],
        max_length=254,
        blank=True,
        null=False,
    )

    room_state = models.CharField(
        "Raum-Status",
        max_length=3,
        choices=ROOM_STATE_CHOICES,
        default=OPEN,
    )

    content_panels = Page.content_panels + [
        FieldPanel("banner_title"),
        FieldPanel("banner_subtitle"),
        FieldPanel("room_state"),
    ]

    class Meta:
        """ Meta informations. """

        verbose_name = "Homepage"
        verbose_name_plural = "Homepages"

home/views.py
import RPi.GPIO as GPIO
import time

from django.http import HttpResponseRedirect

LED_PIN = 5


def turnLEDOn(request):
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(LED_PIN, GPIO.OUT)
    GPIO.output(LED_PIN, 1)
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def turnLEDOff(request):
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(LED_PIN, GPIO.OUT)
    GPIO.output(LED_PIN, 0)
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def toggleLED(request):
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(LED_PIN, GPIO.OUT)
    GPIO.output(LED_PIN, 1)
    time.sleep(5)
    GPIO.output(LED_PIN, 0)
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse

from wagtail.core.models import Page
from wagtail.search.models import Query


def search(request):
    search_query = request.GET.get('query', None)
    page = request.GET.get('page', 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return TemplateResponse(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

home/templates/home/home_page.html
{% extends "base.html" %}
{% load static %}

{% block body_class %}template-homepage{% endblock %}

{% block extra_css %}

{% comment %}
Delete the line below if you're just getting started and want to remove the welcome screen!
{% endcomment %}
<link rel="stylesheet" href="{% static 'css/welcome_page.css' %}">
{% endblock extra_css %}

{% block content %}

{% comment %}
Delete the line below if you're just getting started and want to remove the welcome screen!
{% endcomment %}
{% include 'home/welcome_page.html' %}

{% endblock content %}

mysite/templates/base.html
{% load static wagtailuserbar %}

<!DOCTYPE html>
<html class="no-js" lang="de">

<!-- Auto-reload page every 30 seconds -->
<META HTTP-EQUIV="refresh" CONTENT="30">

<head>
    <meta charset="utf-8" />
    <title>
        {% block title %}
        {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
        {% endblock %}
        {% block title_suffix %}
        {% with self.get_site.site_name as site_name %}
        {% if site_name %}- {{ site_name }}{% endif %}
        {% endwith %}
        {% endblock %}
    </title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {# Global stylesheets #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> -->

    <style>
        .btn {
            position: relative;
            overflow: hidden;
        }

        .btn:after {
            content: "";
            background: #7FDBFF;
            display: block;
            position: absolute;
            padding-top: 300%;
            padding-left: 150%;
            margin-left: -20px !important;
            margin-top: -120%;
            opacity: 0;
            transition: all 8s
        }

        .btn:active:after {
            margin: 0;
            opacity: 1;
            transition: 0s
        }
    </style>
    {% block extra_css %}
    {# Override this in templates to add extra stylesheets #}
    {% endblock %}
</head>

<body class="{% block body_class %}{% endblock %} bg-light">
    <header>
        {# Navigation fixed #}
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand text-uppercase" style="font-size: 32px; font-weight: bold;">Medienwerkstatt</a>
                <a class="navbar-brand text-uppercase" style="font-size: 32px; font-weight: bold;">Raum 5404</a>
            </div>
        </nav>
    </header>

    {% wagtailuserbar %}

    {% block content %}{% endblock %}

    <main>
        {% if self.get_room_state_display == "Bitte nicht stören!" %}

        <!-- do not show doorbell -->

        {% elif self.get_room_state_display == "Wir haben geöffnet!" or "Wir haben geschlossen!" %}

        <!-- "Tuerklingel" wird auf jeder Seite benoetigt, daher hier in der base.html -->
        <a type="button" href="ledtoggle/" class=" text-center btn btn-primary rounded-pill p-2"
            style="height: 120px; width: 90%; margin: 0 auto; display: block; font-size: 30px;">
            <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-bell"
                viewBox="0 0 16 16">
                <path
                    d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z">
                </path>
            </svg>
            <br />Türklingel
        </a>

        {% endif %}
    </main>

    {# Global javascript #}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
    
    <!-- <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script> -->

    {% block extra_js %}
    {# Override this in templates to add extra javascript #}
    {% endblock %}
</body>

</html>

mysite/templates/home/home_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block content %}

<!-- MOTD -->
<div class="p-5 rounded rounded-lg m-3 text-white bg-secondary" style="height: 270px; margin-top: 40px !important;">

    <h1 class="display-4 border-bottom" style="font-size: 50px;">{{ self.banner_title }}</h1>

    <div class="lead" style="font-size: 25px; margin-top: 20px;">{{ self.banner_subtitle|richtext }}</div>
</div>

<!-- Room state -->
{% if self.get_room_state_display == 'Bitte nicht stören!' %}
<div class="p-5 rounded rounded-lg m-3 display-4 bg-danger text-center text-uppercase text-white font-weight-bold"
    style="height: 125px; padding-top: 30px !important; padding-bottom: 15px !important; font-weight: bold; letter-spacing: 2px;"
    <h1>{{ self.get_room_state_display }}</h1>
</div>

{% elif self.get_room_state_display == 'Wir haben geöffnet!' %}
<div class="p-5 rounded rounded-lg m-3 display-4 bg-success text-center text-uppercase text-white font-weight-bold"
    style="height: 125px; padding-top: 30px !important; padding-bottom: 15px !important; font-weight: bold; letter-spacing: 2px;"
    <h1>{{ self.get_room_state_display }}</h1>
</div>

{% elif self.get_room_state_display == 'Wir haben geschlossen!' %}
<div class="p-5 rounded rounded-lg m-3 display-4 bg-warning text-center text-uppercase text-white font-weight-bold"
    style="height: 125px; padding-top: 30px !important; padding-bottom: 15px !important; font-weight: bold; letter-spacing: 2px;"
    <h1>{{ self.get_room_state_display }}</h1>
</div>

{% endif %}

{% endblock %}

search/templates/search/search.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-searchresults{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}
    <h1>Search</h1>

    <form action="{% url 'search' %}" method="get">
        <input type="text" name="query"{% if search_query %} value="{{ search_query }}"{% endif %}>
        <input type="submit" value="Search" class="button">
    </form>

    {% if search_results %}
        <ul>
            {% for result in search_results %}
                <li>
                    <h4><a href="{% pageurl result %}">{{ result }}</a></h4>
                    {% if result.search_description %}
                        {{ result.search_description }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

        {% if search_results.has_previous %}
            <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.previous_page_number }}">Previous</a>
        {% endif %}

        {% if search_results.has_next %}
            <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.next_page_number }}">Next</a>
        {% endif %}
    {% elif search_query %}
        No results found
    {% endif %}
{% endblock %}